[server]
# Production server configuration
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
# Disable automatic browser opening for production
gatherUsageStats = false
serverAddress = "localhost"

[theme]
# Clean theme for production
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Production client settings
showErrorDetails = false
toolbarMode = "minimal"

[logger]
# Production logging
level = "warning"
messageFormat = "%(asctime)s %(message)s"